sy on
se nu rnu bs=2 sw=4 ts=4 hls ls=2 si acd bo=all mouse=a
map <F9> :w<bar>!g++ "%" -o %:r -std=c++17 -Wall -Wextra -Wshadow -O2 -Dzisk -g -fsanitize=undefined,address<CR>
map <F8> :!./%:r<CR>
inoremap {<CR> {<CR>}<ESC>ko
# -D_GLIBCXX_ASSERTIONS, -D_GLIBCXX_DEBUG
