sy on
se nu rnu bs=2 sw=4 ts=4 hls ls=2 si acd bo=all mouse=a et
map <F9> :w<bar>!g++ "%" -o %:r -std=c++17 -Wall -Wextra -Wshadow -Dzisk -g -fsanitize=undefined,address<CR>
map <F8> :!./%:r<CR>
map <C-a> <ESC>ggVG
inoremap {<CR> {<CR>}<ESC>ko
